name: Checkov and Snyk Vulnerability Scan
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@v12.1347.0
        with:
          directory: terraform/azure/
          framework: terraform 
          api-key: ${{secrets.BRIDGECREW_API_KEY}}
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Snyk monitor
        run: snyk iac test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}          
